### ISSUE TITLE
What type of certificates can be used to sign? 

### ISSUE THREAD

**Issue by lrosenthol** [dimich-g/webpackage#16]
What is the expectation of what types of certificates can be used to sign these packages? 

SSL/TLS?
Code signing?
Standard document/message signing?
Other?

**Comment by bmeck** [comment]
@lrosenthol do we need to constrain the types of certs or just the certificate container format: x509 vs PGP vs ...?

**Comment by lrosenthol** [comment]
@bmeck Yes, we would need both.  First the certificate format (eg. X509 vs. PGP) and then second the type of cert - because you can't necessarily intermix SSL/TLS certs with code or document signing certs.  (which is, of course, by design)

**Comment by lrosenthol** [comment]
@bmeck

It's pretty difficult to get a code signing cert, due to the normal usage
cases for it.   And timestamping even more so - since that's really only
for use in a timestamp server.

But can't hurt to ask...

**Comment by dimich-g** [comment]
Was id-kp-codeSigning extension introduced to be able to issue those separately from SSL (and even using separate roots?) to reduce associated risks? 

Perhaps the limits on key usage (especially key usage extensions) should be a detail of implementation? For example, a browser would use SSL/TLS keys since the content it will validate is web content and the purpose of validation is to afford it the same privileges that delivering it via SSL provides. It is also likely that the procedure to sign the web content will involve the same certs the web servers use already. 

The code distribution tools for JS runtimes may have different limits and require different type of keys (if this is practical).

**Comment by lrosenthol** [comment]
Given that we have identified at least three different use cases for this
work (browsers loading scripts/etc, application packagers and
publications), each of which would logically want/require a different type
of certificate - perhaps we shouldn't put any restrictions here and leave
it up to the use case in question to create a "profile" for their own
needs??

**Comment by bmeck** [comment]
@lrosenthol @dimich-g if we want to leave it up to env that seems fine.
