### ISSUE TITLE
Interfacing with Resource Hints and link rel=preload.

### ISSUE THREAD

**Issue by addyosmani** [dimich-g/webpackage#2]
Something unclear reading through the current proposal is how a developer would hint that some resources in a web package have a higher priority to fetch (e.g via resource hints) than others - the entire package would be fetched with a single priority. If I want to prefetch or preload certain assets, I'm unsure how those systems interface with packages.

Are there any thoughts about this?

**Comment by bmeck** [comment]
@addyosmani I'm not sure that is possible under current text since is a single non-multiplexed body for the payload. You might want to put the prioritized resources at the start of the package body. I would be interested more in having multiple streams like http/2 does if you want to interleave resources and/or change priorities dynamically.

**Comment by bmeck** [comment]
@addyosmani after a call, it should be possible to re-order signed content resources as long as a Package-Signature and Content-Index can be recomputed by the server. The server could re-order them into a more optimal order. Might be a good idea to move the discussion to https://github.com/dimich-g/webpackage/issues/11 since that is going to be covering reordering. Is this ok to close?

**Comment by addyosmani** [comment]
Let's close this one up. Thanks for the replies, @bmeck!
