### ISSUE TITLE
relationship to DPUB

### ISSUE THREAD

**Issue by TzviyaSiegman** [dimich-g/webpackage#3]
Very happy to see Packaging reconsidered. The Digital Publishing IG considered this as well. Please see http://w3c.github.io/dpub-pwp-ucr/index.html for our use cases and requirements. We are also looking at Web App Manifest (https://w3c.github.io/manifest/) as a potential mechanism. Our goals are very similar, so it would be helpful to discuss and find common ground.

**Comment by bmeck** [comment]
@TzviyaSiegman it seems possible to place a Web App Manifest within a WebPackage since it is just a JSON file referenced by a `<link>` in HTML. On a glance it seems possible that the "Packaged Web Publication" standard distribution format could be WebPackage for DPUB, however I don't have the breadth of knowledge to say with 100% certainty that the pagination requirement would be related to WebPackage itself (that may be left up to the contents of individual resources within the package).

**Comment by lrosenthol** [comment]
@dauwhe - cool, thanks!  You will need to write a "packager" in order to get all the correct offsets (either that or a hex editor and patience :)).

Signing the bundle is actually a small part of the solution for two security concerns for portable publications.  It doesn't actually get you an origin - since I could potentially resign your package and therefore "reorigin" it, which isn't what a professional publisher would want (and may indeed break the content).  But more importantly, it's actually the verification process (or specifically the establishment of trust) that we need in the publication realm..

**Comment by mrdewitt** [comment]
I'm working on a golang packager script (in the "go/" directory) that will eventually support content-index and signatures.  Stay tuned!  I think a verifier is also a great tool to keep in this repo as well.

**Comment by bmeck** [comment]
@TzviyaSiegman is this clear / ok to close?

**Comment by iherman** [comment]
@bmeck , @TzviyaSiegman is currently on a maternity leave. I think this issue was raised more as a FYI, and more specific technical problems were discussed on more specific issues. I think it is o.k.  to close this issue.

@lrosenthol @dauwhe : what do you think?

**Comment by lrosenthol** [comment]
Yes, fine to close by me.  We will raise other issues as we get to that
point in our development of DPUB
